import{i as u,S as p}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(t){if(t.ep)return;t.ep=!0;const e=o(t);fetch(t.href,e)}})();function f(s){const o=`https://pixabay.com/api/?${new URLSearchParams({key:"43027284-ae8275f6d108abc1bc2578323",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;return fetch(o).then(i=>i.json())}function m(s,r,o){if(s.length<=0)throw o.classList.add("is-hidden"),new Error(u.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"}));const i=s.map(e=>`
          <li class="cards">
          <a href="${e.largeImageURL}"> <img src="${e.webformatURL}" alt="${e.tags}" width="360" height="152"/> </a>
          <div class="card-description">
            <p class="description"><b>Likes</b> ${e.likes}</p>
            <p class="description"><b>Views</b> ${e.views}</p>
            <p class="description"><b>Comments</b> ${e.comments}</p>
            <p class="description"><b>Downloads</b> ${e.downloads}</p>
            </div>
          </li>
      `).join("");r.insertAdjacentHTML("beforeend",i);const t=new p(".gallery a",{captionsData:"alt",captionDelay:250});o.classList.add("is-hidden"),t.refresh()}const a=document.querySelector("#data-input"),c=document.querySelector(".gallery"),l=document.querySelector(".loader"),d=document.querySelector("form");d.addEventListener("submit",s=>{if(s.preventDefault(),console.log("1"),l.classList.remove("is-hidden"),c.innerHTML="",a.value===""){u.show({title:"Error",message:"Please, fill the field to start search images. ",backgroundColor:"#ef4040",position:"topRight"});return}f(a.value).then(r=>m(r.hits,c,l)).catch(r=>console.log(r)),d.reset()});
//# sourceMappingURL=commonHelpers.js.map
